apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visit-counter
  template:
    metadata:
      labels:
        app: visit-counter
    spec:
      containers:
      - name: visit-counter
        image: <account>/visitor-counter
        env:
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis-pass
                key: REDIS_PASS
                optional: false
        ports:
        - containerPort: 5000