apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

configMapGenerator:
- name: redis-config
  files:
  - app-config/redis.conf

resources:
- redis-pv.yaml
- redis-sts.yaml
- redis-svc.yaml